### ISSUE TITLE
Unhandled exception when activating Dark Theme

### ISSUE THREAD

**Issue by AIVAS001** [xatupal/KeeTheme#23]
KeeTheme 0.6.5.0
KeePass 2.43
Windows 10 v1909 (OS Build 18363.535)

I know KeeTheme works because it works on my home system.
At work, however, I get an unhandled exception error

I'm going to take a guess and say it's related to a .Net dependency.
I have installed at work:
v1.0.3705, v1.1.4322, v2.0.50727, v3.0, v4.0.30319

On both systems, KeeTheme is installed using Chocolatey.

---

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at KeeTheme.Decorators.ObjectListViewDecorator.Initialize()
   at KeeTheme.KeeTheme.SetEnable(Boolean enable)
   at KeeTheme.KeeThemeExt.HandleToggleKeeThemeMenuItemClick(Object sender, EventArgs eventArgs)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KPScript
    Assembly Version: 2.42.1.23641
    Win32 Version: 2.42.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/Plugins/KPScript.exe
----------------------------------------
KeeAnywhere
    Assembly Version: 1.5.1.0
    Win32 Version: 1.5.1.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeeTheme
    Assembly Version: 0.6.5.0
    Win32 Version: 0.6.5.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/X1WHstKDJ13WCoFFbX74/KeeTheme.dll
----------------------------------------
KeePassRPC
    Assembly Version: 2.0.34.13800
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/KeePassRPC.dll
----------------------------------------
Fleck2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Fleck2.DLL
----------------------------------------
DomainPublicSuffix
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/DomainPublicSuffix.DLL
----------------------------------------
Jayrock
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.11214.1056
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Jayrock.DLL
----------------------------------------
KeePassWinHello
    Assembly Version: 3.1.1.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/T3qoSU1izJPWJ8p40zkd/KeePassWinHello.dll
----------------------------------------
YetAnotherFaviconDownloader
    Assembly Version: 1.2.2.0
    Win32 Version: 1.2.2.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LbEkluzRJUEVx7JNd67v/YetAnotherFaviconDownloader.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.18739
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
AmazonCloudDriveApi
    Assembly Version: 1.5.5.0
    Win32 Version: 1.5.5
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/AmazonCloudDriveApi.DLL
----------------------------------------
Box.V2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Box.V2.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
AWSSDK.S3
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.18.5
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/AWSSDK.S3.DLL
----------------------------------------
AWSSDK.Core
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.24.2
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/AWSSDK.Core.DLL
----------------------------------------
Dropbox.Api
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.6718
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Dropbox.Api.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.34.0.1239
    Win32 Version: 1.34.0.1239
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.34.0.0
    Win32 Version: 1.34.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Google.Apis.Auth.DLL
----------------------------------------
Kyrodan.HiDrive
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.43
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Kyrodan.HiDrive.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Microsoft.OneDrive.Sdk.Authentication.Desktop
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Microsoft.OneDrive.Sdk.Authentication.Desktop.DLL
----------------------------------------
Microsoft.Graph
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/Microsoft.Graph.DLL
----------------------------------------
Jayrock.Json
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.13422.2206
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Jayrock.Json.DLL
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.15362.1
    CodeBase: file:///C:/Users/atst/AppData/Local/KeePass/PluginCache/LR3irG7BIgmOTPa3kgxj/BouncyCastle.Crypto.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
---

**Comment by xatupal** [comment]
Thanks for info. I'll fix it.
