### ISSUE TITLE
KeeTheme 10.2 not compatible with KeePass 2.54

### ISSUE THREAD

**Issue by The-Experimentalist** [xatupal/KeeTheme#94]
[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
U:\KeePass\Plugins\KeeTheme\KeeTheme.dll

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Could not load file or assembly 'KeePass, Version=2.51.1.15884, Culture=neutral, PublicKeyToken=fed2ed7716aecf5c' or one of its dependencies. The system cannot find the file specified.
mscorlib
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at KeePass.Plugins.PluginManager.CreatePluginInstance(String strFilePath, String strTypeName)
   at KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Void GetType(System.Reflection.RuntimeAssembly, System.String, Boolean, Boolean, System.Runtime.CompilerServices.ObjectHandleOnStack)

[^] Details  [OK]

**Comment by o-l-a-v** [comment]
Hmm. It works for me, but I'm using the `.plgx` file, not the `.dll`.

**Comment by xatupal** [comment]
This is so weird. I've checked KeeTheme in KeePass v2.54 and I can't reproduce the problem.
Do you have any other plugins installed?

**Comment by The-Experimentalist** [comment]
Sorry for the slow reply. Have been very busy. Issue was that I had a subfolder called archive with older versions and Keepass was getting confused. So in my Keepass plugins path looked like this:

\Plugins\KeeTheme\Archive

I had the 10.2 dll and plgx files in:

\Plugins\KeeTheme

... but some older versions in the archive sub folder. I've deleted the archive subfolder now and all is well so please close the issue. Thanks for the plugin and your help

Ex

**Comment by xatupal** [comment]
Thanks for info! Great to hear that it works!
